In [1]:
import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from pycaret.classification import *
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore')

In [2]:
train  = pd.read_csv('competition_data/train.csv')
test  = pd.read_csv('competition_data/test.csv')
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_columns', 100)

In [3]:
train

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,country,introelapse,testelapse,surveyelapse,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,hand,religion,orientation,voted,married,familysize,ASD,nerdiness
0,0,1.0,5.0,5.0,5.0,1.0,4.0,5.0,5.0,1.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,5.0,5.0,1.0,5.0,1.0,5.0,1.0,1.0,USA,3,553,6,4.0,3.0,5.0,1.0,3.0,5.0,5.0,3.0,5.0,3.0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2.0,1,3.0,1.0,20,2.0,12.0,4.0,2.0,1.0,4.0,2.0,1
1,1,4.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,3.0,1.0,4.0,5.0,3.0,1.0,2.0,4.0,5.0,1.0,3.0,1.0,1.0,5.0,3.0,2.0,5.0,USA,5,85,120,4.0,2.0,3.0,5.0,3.0,2.0,5.0,1.0,2.0,2.0,1,1,1,1,1,0,1,0,0,1,0,0,1,1,1,1,4.0,2,2.0,1.0,49,1.0,2.0,1.0,1.0,2.0,4.0,2.0,1
2,2,4.0,5.0,5.0,4.0,3.0,5.0,5.0,5.0,4.0,4.0,2.0,5.0,5.0,5.0,1.0,3.0,5.0,3.0,5.0,2.0,2.0,1.0,2.0,4.0,2.0,5.0,NLD,9,108,100,1.0,2.0,3.0,1.0,5.0,5.0,3.0,4.0,5.0,2.0,1,1,0,1,1,0,1,1,0,1,0,0,1,1,1,1,2.0,1,1.0,2.0,43,1.0,2.0,2.0,2.0,3.0,4.0,2.0,1
3,3,4.0,4.0,4.0,2.0,4.0,3.0,3.0,5.0,3.0,4.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,5.0,4.0,3.0,3.0,4.0,3.0,4.0,4.0,2.0,USA,2,121,139,3.0,3.0,3.0,4.0,5.0,3.0,4.0,4.0,3.0,3.0,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,1.0,3,1.0,1.0,17,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1
4,4,4.0,4.0,4.0,4.0,3.0,3.0,4.0,2.0,3.0,4.0,4.0,4.0,3.0,5.0,5.0,2.0,4.0,1.0,4.0,2.0,4.0,2.0,3.0,4.0,4.0,4.0,ITA,3,640,216,3.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,2.0,1,1,0,1,1,0,0,1,0,1,0,0,0,1,0,1,1.0,2,2.0,2.0,18,2.0,12.0,1.0,2.0,1.0,1.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14995,2.0,5.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,1.0,4.0,4.0,3.0,4.0,4.0,2.0,5.0,2.0,4.0,1.0,2.0,5.0,4.0,2.0,4.0,USA,12,103,161,2.0,2.0,4.0,3.0,3.0,5.0,3.0,3.0,3.0,3.0,1,1,1,1,1,0,0,0,0,1,0,1,1,1,1,1,2.0,2,2.0,1.0,17,1.0,1.0,3.0,2.0,1.0,3.0,2.0,0
14996,14996,5.0,4.0,5.0,4.0,4.0,5.0,5.0,4.0,4.0,5.0,1.0,4.0,4.0,4.0,2.0,5.0,5.0,4.0,1.0,5.0,3.0,4.0,4.0,5.0,4.0,5.0,USA,31,106,179,3.0,2.0,4.0,5.0,4.0,3.0,4.0,1.0,2.0,2.0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,4.0,1,2.0,2.0,45,1.0,3.0,1.0,1.0,2.0,3.0,2.0,1
14997,14997,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,2.0,5.0,5.0,3.0,4.0,USA,17,103,168,1.0,3.0,2.0,5.0,1.0,5.0,3.0,3.0,1.0,1.0,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,2.0,2,2.0,1.0,20,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1
14998,14998,5.0,5.0,4.0,5.0,5.0,5.0,5.0,1.0,5.0,5.0,3.0,5.0,4.0,4.0,1.0,5.0,4.0,5.0,5.0,2.0,5.0,3.0,5.0,3.0,3.0,5.0,USA,14,68,109,1.0,1.0,3.0,5.0,4.0,5.0,5.0,4.0,2.0,1.0,1,1,1,1,1,0,0,1,0,1,0,1,1,1,1,1,3.0,2,2.0,1.0,29,1.0,12.0,4.0,2.0,2.0,2.0,1.0,0
14999,14999,5.0,4.0,2.0,5.0,2.0,2.0,4.0,2.0,4.0,4.0,4.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,5.0,3.0,4.0,2.0,3.0,4.0,3.0,4.0,BRA,8,182,348,4.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,3.0,2.0,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,2.0,3,1.0,2.0,21,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1

In [4]:
train.head()

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,country,introelapse,testelapse,surveyelapse,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,hand,religion,orientation,voted,married,familysize,ASD,nerdiness
0,0,1.0,5.0,5.0,5.0,1.0,4.0,5.0,5.0,1.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,5.0,5.0,1.0,5.0,1.0,5.0,1.0,1.0,USA,3,553,6,4.0,3.0,5.0,1.0,3.0,5.0,5.0,3.0,5.0,3.0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2.0,1,3.0,1.0,20,2.0,12.0,4.0,2.0,1.0,4.0,2.0,1
1,1,4.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,3.0,1.0,4.0,5.0,3.0,1.0,2.0,4.0,5.0,1.0,3.0,1.0,1.0,5.0,3.0,2.0,5.0,USA,5,85,120,4.0,2.0,3.0,5.0,3.0,2.0,5.0,1.0,2.0,2.0,1,1,1,1,1,0,1,0,0,1,0,0,1,1,1,1,4.0,2,2.0,1.0,49,1.0,2.0,1.0,1.0,2.0,4.0,2.0,1
2,2,4.0,5.0,5.0,4.0,3.0,5.0,5.0,5.0,4.0,4.0,2.0,5.0,5.0,5.0,1.0,3.0,5.0,3.0,5.0,2.0,2.0,1.0,2.0,4.0,2.0,5.0,NLD,9,108,100,1.0,2.0,3.0,1.0,5.0,5.0,3.0,4.0,5.0,2.0,1,1,0,1,1,0,1,1,0,1,0,0,1,1,1,1,2.0,1,1.0,2.0,43,1.0,2.0,2.0,2.0,3.0,4.0,2.0,1
3,3,4.0,4.0,4.0,2.0,4.0,3.0,3.0,5.0,3.0,4.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,5.0,4.0,3.0,3.0,4.0,3.0,4.0,4.0,2.0,USA,2,121,139,3.0,3.0,3.0,4.0,5.0,3.0,4.0,4.0,3.0,3.0,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,1.0,3,1.0,1.0,17,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1
4,4,4.0,4.0,4.0,4.0,3.0,3.0,4.0,2.0,3.0,4.0,4.0,4.0,3.0,5.0,5.0,2.0,4.0,1.0,4.0,2.0,4.0,2.0,3.0,4.0,4.0,4.0,ITA,3,640,216,3.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,2.0,1,1,0,1,1,0,0,1,0,1,0,0,0,1,0,1,1.0,2,2.0,2.0,18,2.0,12.0,1.0,2.0,1.0,1.0,2.0,0

In [5]:
train = train.drop(['index', 'country'],axis = 1)
test =test.drop(['index', 'country'],axis = 1)

In [6]:
clf = setup(data = train, target = 'nerdiness')

In [7]:
best_3 = compare_models(sort = 'AUC', n_select = 3)

In [8]:
et = create_model('et')
rf = create_model('rf')

In [9]:
blended = blend_models([et,rf], weights = [0.8,0.2], fold = 10, method = 'soft')

In [11]:
tuned_blender = tune_model(blended,optimize='AUC',n_iter=50)

In [12]:
pred_holdout = predict_model(tuned_blender)

In [20]:
final_model = finalize_model(tuned_blender)

ValueError: Estimator       introelapse  testelapse  surveyelapse   age  Q1_1.0  Q1_2.0  Q1_3.0  \
0             2.0        61.0          94.0  16.0     0.0     0.0     0.0
1          6910.0       174.0         297.0  49.0     0.0     0.0     0.0
2             7.0       417.0         219.0  20.0     0.0     0.0     0.0
3             3.0       106.0         133.0  14.0     0.0     0.0     0.0
4            19.0       108.0          90.0  38.0     0.0     0.0     0.0
...           ...         ...           ...   ...     ...     ...     ...
4496        422.0        72.0          87.0  26.0     0.0     0.0     0.0
4497         37.0       155.0         174.0  17.0     0.0     0.0     1.0
4498          3.0       114.0         411.0  34.0     0.0     0.0     0.0
4499          2.0        72.0         108.0  29.0     0.0     0.0     0.0
4500          2.0       107.0         163.0  20.0     0.0     0.0     0.0

      Q1_4.0  Q1_5.0  Q1_not_available  ...  familysize_7.0  familysize_8.0  \
0        1.0     0.0               0.0  ...             0.0             0.0
1        1.0     0.0               0.0  ...             0.0             0.0
2        1.0     0.0               0.0  ...             0.0             0.0
3        0.0     1.0               0.0  ...             0.0             0.0
4        1.0     0.0               0.0  ...             0.0             0.0
...      ...     ...               ...  ...             ...             ...
4496     0.0     1.0               0.0  ...             0.0             0.0
4497     0.0     0.0               0.0  ...             0.0             0.0
4498     0.0     1.0               0.0  ...             0.0             0.0
4499     1.0     0.0               0.0  ...             0.0             0.0
4500     1.0     0.0               0.0  ...             0.0             0.0

      familysize_9.0  familysize_not_available  ASD_1.0  ASD_2.0  \
0                0.0                       0.0      0.0      1.0
1                0.0                       0.0      0.0      1.0
2                0.0                       0.0      0.0      1.0
3                0.0                       0.0      0.0      1.0
4                0.0                       0.0      0.0      1.0
...              ...                       ...      ...      ...
4496             0.0                       0.0      0.0      1.0
4497             0.0                       0.0      0.0      1.0
4498             0.0                       0.0      0.0      1.0
4499             0.0                       0.0      0.0      1.0
4500             0.0                       0.0      0.0      1.0

      ASD_not_available  nerdiness  Label   Score
0                   0.0          1      0  0.5514
1                   0.0          1      1  0.9186
2                   0.0          0      1  0.5757
3                   0.0          1      1  0.8971
4                   0.0          0      0  0.5043
...                 ...        ...    ...     ...
4496                0.0          1      1  0.6971
4497                0.0          0      0  0.8643
4498                0.0          0      1  0.7771
4499                0.0          1      1  0.9786
4500                0.0          1      1  0.6800

[4501 rows x 307 columns] does not have the required fit() method.

In [14]:
predictions = predict_model(final_model, data = test)

In [15]:
predictions

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,age,hand,religion,orientation,voted,married,familysize,ASD,Label,Score
0,4.0,4.0,3.0,5.0,5.0,5.0,3.0,5.0,4.0,5.0,...,19,1.0,4.0,4.0,1.0,1.0,3.0,2.0,0,0.9229
1,4.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,4.0,...,33,1.0,1.0,5.0,2.0,1.0,5.0,2.0,1,0.7371
2,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,4.0,...,13,1.0,4.0,5.0,2.0,1.0,3.0,2.0,1,0.8271
3,5.0,4.0,3.0,4.0,5.0,4.0,5.0,4.0,4.0,5.0,...,28,1.0,2.0,2.0,2.0,1.0,3.0,2.0,1,0.6229
4,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,5.0,5.0,...,15,1.0,4.0,5.0,2.0,1.0,2.0,2.0,1,0.9614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35447,4.0,5.0,5.0,3.0,3.0,4.0,5.0,5.0,4.0,3.0,...,16,3.0,10.0,4.0,2.0,1.0,3.0,2.0,1,0.9314
35448,5.0,5.0,5.0,5.0,5.0,4.0,5.0,3.0,5.0,3.0,...,16,3.0,2.0,5.0,2.0,1.0,2.0,2.0,1,0.7429
35449,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,31,1.0,1.0,5.0,1.0,1.0,2.0,2.0,1,0.9314
35450,5.0,5.0,4.0,5.0,5.0,1.0,5.0,1.0,5.0,5.0,...,19,1.0,12.0,1.0,2.0,1.0,NaN,2.0,0,0.8671
35451,5.0,5.0,4.0,5.0,2.0,4.0,3.0,5.0,4.0,5.0,...,14,2.0,NaN,2.0,2.0,1.0,1.0,2.0,1,0.6614

In [16]:
submission = pd.read_csv('competition_data/sample_submission.csv')

submission

       index  nerdiness
0          0         -1
1          1         -1
2          2         -1
3          3         -1
4          4         -1
...      ...        ...
35447  35447         -1
35448  35448         -1
35449  35449         -1
35450  35450         -1
35451  35451         -1

[35452 rows x 2 columns]

In [17]:
submission['nerdiness'] = predictions['Label']

In [18]:
submission

       index  nerdiness
0          0          0
1          1          1
2          2          1
3          3          1
4          4          1
...      ...        ...
35447  35447          1
35448  35448          1
35449  35449          1
35450  35450          0
35451  35451          1

[35452 rows x 2 columns]

여기까지임

In [19]:
submission.to_csv("hard-cha.csv", index = False)